export type DietaryTag = "All" | "Vegetarian" | "Non-Vegetarian" | "Gluten-Free" | "Chef's Selection";

export type MenuItem = {
  id: string;
  name: string;
  description: string;
  price: number;
  badge?: "VEGETARIAN" | "POPULAR" | "CHEF'S PICK" | "HOUSE FAVOURITE";
  image: string;
  dietary: DietaryTag[];
  calories?: string;
  prepTime?: string;
  winePairing?: string;
  ingredients?: string[];
};

export type MenuCategoryData = {
  id: string;
  label: string;
  icon: "starters" | "mains" | "pasta" | "pizza" | "salads" | "desserts" | "beverages";
  count: number;
  eyebrow: string;
  title: string;
  subtitle: string;
  collectionBadge: string;
  bannerImage: string;
  items: MenuItem[];
};

export const FULL_MENU_CATEGORIES: MenuCategoryData[] = [
  {
    id: "starters",
    label: "Starters",
    icon: "starters",
    count: 3,
    eyebrow: "APPETIZERS & MEZZE",
    title: "Starters",
    subtitle: "Small plates. Big flavors. Designed for sharing.",
    collectionBadge: "SIGNATURE COLLECTION",
    bannerImage: "/images/sauce-pour-banner.jpg",
    items: [
      {
        id: "truffle-bruschetta",
        name: "Truffle Mushroom Bruschetta",
        description: "Charred artisanal sourdough, wild forest mushrooms, fresh thyme crema, black truffle...",
        price: 12,
        badge: "VEGETARIAN",
        image: "/images/truffle-bruschetta.jpg",
        dietary: ["All", "Vegetarian", "Chef's Selection"],
        winePairing: "Château Ksara Blanc de Blancs 2021",
        ingredients: ["Artisanal Sourdough", "Porcini & Chanterelles", "Thyme Crema", "Norcia Black Truffle", "Cold-Pressed Olive Oil"],
        calories: "340 kcal",
      },
      {
        id: "crispy-calamari",
        name: "Crispy Calamari",
        description: "Tender flash-fried Mediterranean calamari, charred citrus aioli, micro herbs, sumac sea...",
        price: 14,
        badge: "POPULAR",
        image: "/images/crispy-calamari.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Massaya Rosé 2022, Bekaa Valley",
        ingredients: ["Mediterranean Calamari", "Citrus Aioli", "Sumac", "Fresh Micro Dill", "Charred Meyer Lemon"],
        calories: "420 kcal",
      },
      {
        id: "spicy-chicken-wings",
        name: "Spicy Chicken Wings",
        description: "Woodfire-glazed organic wings, pomegranate chili glaze, roasted sesame, fresh coriander...",
        price: 16,
        badge: "CHEF'S PICK",
        image: "/images/spicy-chicken-wings.jpg",
        dietary: ["All", "Non-Vegetarian", "Chef's Selection"],
        winePairing: "Domaine des Tourelles Red 2020",
        ingredients: ["Organic Chicken", "Pomegranate Molasses", "Aleppo Chili", "Toasted Sesame", "Garden Coriander"],
        calories: "480 kcal",
      },
      {
        id: "hummus-tahini-royale",
        name: "Hummus & Tahini Royale",
        description: "Warm organic chickpeas, stone-milled sesame tahini, cold-pressed olive oil, za'atar crisps.",
        price: 11,
        badge: "VEGETARIAN",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Ixsir Altitudes White 2022",
        ingredients: ["Organic Chickpeas", "Stone-Milled Tahini", "Wild Za'atar", "Baladi Olive Oil"],
        calories: "290 kcal",
      },
      {
        id: "levantine-fattoush",
        name: "Levantine Fattoush",
        description: "Garden leaves, heirloom radishes, ruby sumac, pomegranate molasses, crisp whole-wheat pita.",
        price: 13,
        badge: "POPULAR",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian"],
        winePairing: "Château Musar Jeune Rosé 2021",
        ingredients: ["Heirloom Leaves", "Ruby Sumac", "Pomegranate Molasses", "Crisp Pita", "Mint"],
        calories: "240 kcal",
      },
      {
        id: "lamb-arayes-maza",
        name: "Lamb Arayes Al-Maza",
        description: "Spiced Awassi minced lamb pressed in thin griddle bread, served with whipped garlic toum.",
        price: 17,
        badge: "CHEF'S PICK",
        image: "/images/dish-chicken.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Château Kefraya Les Bretèches 2019",
        ingredients: ["Awassi Lamb", "Lebanese Seven Spices", "Griddle Bread", "Garlic Toum"],
        calories: "510 kcal",
      },
    ],
  },
  {
    id: "mains",
    label: "Main Course",
    icon: "mains",
    count: 4,
    eyebrow: "FIRE & SLOW-COOKED",
    title: "Main Course",
    subtitle: "The centrepiece of the table — flame-finished, slow-cooked, generous.",
    collectionBadge: "SIGNATURE COLLECTION",
    bannerImage: "/images/sauce-pour-banner.jpg",
    items: [
      {
        id: "charred-lamb-chops",
        name: "Charred Lamb Chops",
        description: "Rosemary jus, grilled lemon, blistered vine tomatoes and crushed fingerling potatoes.",
        price: 34,
        badge: "CHEF'S PICK",
        image: "/images/sauce-pour-banner.jpg",
        dietary: ["All", "Non-Vegetarian", "Chef's Selection", "Gluten-Free"],
        winePairing: "Château Musar Red 2016",
        ingredients: ["Coastal Lamb", "Mountain Rosemary Jus", "Grilled Lemon", "Fleur de Sel"],
        calories: "680 kcal",
      },
      {
        id: "braised-short-rib",
        name: "Braised Short Rib",
        description: "14-hour braised Angus rib, Lebanese baharat spice, caramelized root vegetables & silky mash.",
        price: 32,
        badge: "POPULAR",
        image: "/images/sauce-pour-banner.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Château Marsyas Red 2017",
        ingredients: ["Prime Angus Rib", "Baharat Spices", "Bone Marrow Glaze", "Root Vegetables"],
        calories: "740 kcal",
      },
      {
        id: "grilled-sea-bass",
        name: "Grilled Sea Bass",
        description: "Wild Mediterranean sea bass, Levantine herb crust, fennel compote and golden saffron broth.",
        price: 31,
        badge: "CHEF'S PICK",
        image: "/images/dish-chicken.jpg",
        dietary: ["All", "Non-Vegetarian", "Gluten-Free", "Chef's Selection"],
        winePairing: "Ixsir Grande Réserve White 2020",
        ingredients: ["Wild Sea Bass", "Herb Crust", "Fennel Compote", "Saffron Broth"],
        calories: "490 kcal",
      },
      {
        id: "grilled-lavender-chicken",
        name: "Grilled Lavender Chicken",
        description: "Free-range chicken breast infused with Provence lavender, baby glazed carrots and savory jus.",
        price: 22,
        badge: "POPULAR",
        image: "/images/dish-chicken.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Château St Thomas Chardonnay 2021",
        ingredients: ["Free-Range Chicken", "French Lavender", "Glazed Baby Carrots", "Herb Jus"],
        calories: "520 kcal",
      },
    ],
  },
  {
    id: "pasta",
    label: "Pasta",
    icon: "pasta",
    count: 6,
    eyebrow: "HAND-ROLLED & ALL'ONDA",
    title: "Pasta & Risotto",
    subtitle: "Silk-thin pasta and all'onda rice, finished to order with fragrant butter and truffle.",
    collectionBadge: "CHEF'S ATELIER",
    bannerImage: "/images/dish-risotto.jpg",
    items: [
      {
        id: "lobster-linguine",
        name: "Lobster Linguine",
        description: "Hand-rolled silk pasta, Brittany blue lobster, brown butter, smoked n'duja and Meyer lemon.",
        price: 29,
        badge: "CHEF'S PICK",
        image: "/images/dish-risotto.jpg",
        dietary: ["All", "Non-Vegetarian", "Chef's Selection"],
        winePairing: "Château Kefraya Blanc de Blancs",
        ingredients: ["Hand-Rolled Pasta", "Blue Lobster", "Brown Butter", "Smoked N'duja"],
        calories: "590 kcal",
      },
      {
        id: "truffle-mushroom-risotto",
        name: "Truffle Mushroom Risotto",
        description: "Arborio rice, wild forest porcini, aged parmesan & freshly shaved black Norcia truffle.",
        price: 18,
        badge: "VEGETARIAN",
        image: "/images/dish-risotto.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free", "Chef's Selection"],
        winePairing: "Massaya Gold Reserve 2018",
        ingredients: ["Acquerello Rice", "Wild Porcini", "Aged 24m Parmesan", "Norcia Truffle"],
        calories: "510 kcal",
      },
      {
        id: "saffron-orzo-lamb",
        name: "Saffron Orzo with Lamb",
        description: "Slow-simmered lamb stock, toasted orzo pasta, Persian saffron and golden toasted almonds.",
        price: 21,
        badge: "POPULAR",
        image: "/images/dish-risotto.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Château Ksara Cuvée du Troisième Millénaire",
        ingredients: ["Greek Orzo", "Lamb Broth", "Persian Saffron", "Toasted Almonds"],
        calories: "560 kcal",
      },
      {
        id: "aubergine-maklouba-pasta",
        name: "Aubergine Maklouba Pasta",
        description: "Campanelle curls, caramelized baby eggplant, San Marzano tomato reduction, toasted pine nuts.",
        price: 16,
        badge: "VEGETARIAN",
        image: "/images/dish-risotto.jpg",
        dietary: ["All", "Vegetarian"],
        winePairing: "Ixsir Altitudes Red 2019",
        ingredients: ["Campanelle Pasta", "Caramelized Eggplant", "San Marzano", "Pine Nuts"],
        calories: "440 kcal",
      },
      {
        id: "spinach-ricotta-ravioli",
        name: "Spinach & Ricotta Ravioli",
        description: "Hand-pinched pasta pillows, buffalo milk ricotta, crisp sage leaves and noisette brown butter.",
        price: 19,
        badge: "VEGETARIAN",
        image: "/images/truffle-bruschetta.jpg",
        dietary: ["All", "Vegetarian"],
        winePairing: "Château Musar White 2014",
        ingredients: ["Buffalo Ricotta", "Garden Spinach", "Sage Noisette", "Parmesano"],
        calories: "480 kcal",
      },
      {
        id: "nero-di-seppia",
        name: "Spaghetti Nero Di Seppia",
        description: "Squid ink artisanal spaghetti, sautéed baby calamari, cured mullet bottarga and red chili oil.",
        price: 26,
        badge: "CHEF'S PICK",
        image: "/images/crispy-calamari.jpg",
        dietary: ["All", "Non-Vegetarian", "Chef's Selection"],
        winePairing: "Massaya White 2021",
        ingredients: ["Squid Ink Pasta", "Baby Calamari", "Sardinian Bottarga", "Garlic Chili Oil"],
        calories: "520 kcal",
      },
    ],
  },
  {
    id: "pizza",
    label: "Pizza",
    icon: "pizza",
    count: 6,
    eyebrow: "WOODFIRE STONE OVEN",
    title: "Artisanal Pizza",
    subtitle: "48-hour fermented sourdough crust, blistered at 450°C over olive wood.",
    collectionBadge: "STONE OVEN SPECIAL",
    bannerImage: "/images/truffle-bruschetta.jpg",
    items: [
      {
        id: "truffle-taleggio-pizza",
        name: "Black Truffle & Taleggio",
        description: "Sourdough crust, melted taleggio, fior di latte, white truffle crema and fresh Norcia carpaccio.",
        price: 22,
        badge: "VEGETARIAN",
        image: "/images/truffle-bruschetta.jpg",
        dietary: ["All", "Vegetarian", "Chef's Selection"],
        winePairing: "Château Ksara Chardonnay 2022",
        ingredients: ["48h Sourdough", "Taleggio D.O.P.", "Fior di Latte", "Norcia Truffle"],
        calories: "780 kcal",
      },
      {
        id: "spiced-lamb-pizza",
        name: "Spiced Lamb & Pine Nut",
        description: "Woodfire crust, spiced lamb confit, pickled shallots, minted labneh swirl, toasted pine nuts.",
        price: 24,
        badge: "CHEF'S PICK",
        image: "/images/sauce-pour-banner.jpg",
        dietary: ["All", "Non-Vegetarian", "Chef's Selection"],
        winePairing: "Château Kefraya Red 2018",
        ingredients: ["Sourdough", "Spiced Lamb Confit", "Minted Labneh", "Pine Nuts"],
        calories: "820 kcal",
      },
      {
        id: "charred-fig-bresaola",
        name: "Charred Fig & Bresaola",
        description: "Sweet mission figs, cured beef bresaola, gorgonzola dolce, wild arugula and balsamic glaze.",
        price: 21,
        badge: "POPULAR",
        image: "/images/truffle-bruschetta.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Massaya Le Colombier 2020",
        ingredients: ["Mission Figs", "Beef Bresaola", "Gorgonzola Dolce", "Aged Balsamic"],
        calories: "740 kcal",
      },
      {
        id: "classic-margherita-dop",
        name: "Margherita D.O.P.",
        description: "San Marzano tomatoes, Campania buffalo mozzarella, torn sweet basil and cold-pressed olive oil.",
        price: 17,
        badge: "VEGETARIAN",
        image: "/images/truffle-bruschetta.jpg",
        dietary: ["All", "Vegetarian"],
        winePairing: "Domaine des Tourelles Rosé",
        ingredients: ["San Marzano D.O.P.", "Buffalo Mozzarella", "Fresh Basil", "EVOO"],
        calories: "690 kcal",
      },
      {
        id: "smoked-burrata-zaatar",
        name: "Smoked Burrata & Za'atar",
        description: "Whole smoked burrata, wild mountain za'atar, blistered cherry tomatoes and spicy chili honey.",
        price: 20,
        badge: "VEGETARIAN",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian"],
        winePairing: "Ixsir Altitudes White 2021",
        ingredients: ["Smoked Burrata", "Wild Za'atar", "Confit Tomatoes", "Hot Honey"],
        calories: "760 kcal",
      },
      {
        id: "diavola-di-mare",
        name: "Diavola Di Mare",
        description: "Spicy calabrian nduja, wood-fired prawns, roasted garlic oil, fior di latte and oregano.",
        price: 25,
        badge: "CHEF'S PICK",
        image: "/images/crispy-calamari.jpg",
        dietary: ["All", "Non-Vegetarian"],
        winePairing: "Château St Thomas Pinot Noir",
        ingredients: ["Tiger Prawns", "Spicy Nduja", "Fior di Latte", "Roasted Garlic"],
        calories: "790 kcal",
      },
    ],
  },
  {
    id: "salads",
    label: "Salads",
    icon: "salads",
    count: 5,
    eyebrow: "GARDEN & HARVEST",
    title: "Salads & Crudités",
    subtitle: "Picked before the sun lifts — wild herbs, heirloom greens, and stone-pressed oils.",
    collectionBadge: "ESTATE HARVEST",
    bannerImage: "/images/pea-soup.png",
    items: [
      {
        id: "heirloom-burrata-peach",
        name: "Heirloom Burrata & Peach",
        description: "Handcrafted burrata, grilled Levantine peaches, pistachio dukkah, wild blossom honey.",
        price: 18,
        badge: "VEGETARIAN",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free", "Chef's Selection"],
        winePairing: "Château Ksara Blanc de Blancs",
        ingredients: ["Pugliese Burrata", "Grilled Peaches", "Pistachio Dukkah", "Orange Blossom Honey"],
        calories: "380 kcal",
      },
      {
        id: "wild-zaatar-halloumi",
        name: "Wild Za'atar & Halloumi",
        description: "Fresh green mountain za'atar leaves, griddled sheep's milk halloumi, cherry tomatoes and sumac.",
        price: 16,
        badge: "POPULAR",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Château Kefraya Myst Rosé",
        ingredients: ["Green Za'atar", "Griddled Halloumi", "Heirloom Tomatoes", "Sumac"],
        calories: "340 kcal",
      },
      {
        id: "truffle-caesar-salad",
        name: "Baby Gem & Truffle Caesar",
        description: "Crisp baby romaine, shaved aged parmesan, brioche croutons, white truffle Caesar dressing.",
        price: 15,
        badge: "CHEF'S PICK",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian"],
        winePairing: "Ixsir Grande Réserve White",
        ingredients: ["Baby Gem Lettuce", "24m Parmesan", "Brioche Croutons", "Truffle Dressing"],
        calories: "320 kcal",
      },
      {
        id: "roasted-beet-labneh",
        name: "Roasted Beetroot & Goat Labneh",
        description: "Salt-baked golden beets, whipped goat labneh, candied walnuts, orange zest and wild thyme.",
        price: 15,
        badge: "VEGETARIAN",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Château Musar Jeune White",
        ingredients: ["Golden & Red Beets", "Goat Labneh", "Candied Walnuts", "Orange Zest"],
        calories: "310 kcal",
      },
      {
        id: "tabbouleh-al-haute",
        name: "Tabbouleh Al-Haute",
        description: "Finely sliced flat parsley, quinoa crunch, sweet vine tomatoes, fresh mint and lemon oil.",
        price: 14,
        badge: "POPULAR",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Massaya Classic White",
        ingredients: ["Garden Parsley", "Crisp Quinoa", "Sweet Tomatoes", "Meyer Lemon"],
        calories: "220 kcal",
      },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    icon: "desserts",
    count: 7,
    eyebrow: "A QUIET, SWEET FINALE",
    title: "Desserts & Confections",
    subtitle: "A quiet, sweet finale — restrained, fragrant, and beautifully handcrafted.",
    collectionBadge: "PATISSERIE RESERVE",
    bannerImage: "/images/dish-lava-cake.jpg",
    items: [
      {
        id: "valrhona-lava-cake",
        name: "Chocolate Lava Cake",
        description: "Valrhona dark chocolate molten centre served warm with Tahitian vanilla bean gelato.",
        price: 12,
        badge: "POPULAR",
        image: "/images/dish-lava-cake.jpg",
        dietary: ["All", "Vegetarian", "Chef's Selection"],
        winePairing: "Château Ksara Moscatel",
        ingredients: ["Valrhona 70% Chocolate", "Tahitian Vanilla Gelato", "Cocoa Crumble"],
        calories: "490 kcal",
      },
      {
        id: "seasonal-fruit-tart",
        name: "Seasonal Fruit Tart",
        description: "Crisp shortbread crust, Madagascar pastry cream, glazed summer berries and organic garden mint.",
        price: 10,
        badge: "VEGETARIAN",
        image: "/images/dish-fruit-tart.jpg",
        dietary: ["All", "Vegetarian"],
        winePairing: "Massaya Arak & Mint",
        ingredients: ["Pâte Sablée", "Vanilla Pastry Cream", "Glazed Berries", "Garden Mint"],
        calories: "380 kcal",
      },
      {
        id: "pistachio-baklava-ashta",
        name: "Baklava & Ashta",
        description: "Crisp filo pastry, clotted ashta cream, hand-pounded Antep pistachios, orange blossom syrup.",
        price: 13,
        badge: "CHEF'S PICK",
        image: "/images/dish-lava-cake.jpg",
        dietary: ["All", "Vegetarian", "Chef's Selection"],
        winePairing: "Traditional Turkish / Lebanese Coffee",
        ingredients: ["Filo Pastry", "Clotted Ashta", "Antep Pistachios", "Orange Blossom Syrup"],
        calories: "440 kcal",
      },
      {
        id: "rosewater-mouhalabia",
        name: "Rosewater Mouhalabia",
        description: "Silky Lebanese milk pudding, candied rose petals, toasted slivered almonds and orange blossom.",
        price: 11,
        badge: "VEGETARIAN",
        image: "/images/dish-fruit-tart.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Château Kefraya Lacrima D'Oro",
        ingredients: ["Organic Whole Milk", "Rosewater", "Toasted Almonds", "Candied Petals"],
        calories: "280 kcal",
      },
      {
        id: "cardamom-date-pudding",
        name: "Cardamom Date Pudding",
        description: "Warm Medjool date sponge, rich toffee caramel reduction and clotted cream gelato.",
        price: 14,
        badge: "POPULAR",
        image: "/images/dish-lava-cake.jpg",
        dietary: ["All", "Vegetarian"],
        winePairing: "Single Malt Speyside 12y",
        ingredients: ["Medjool Dates", "Toffee Caramel", "Cardamom", "Clotted Gelato"],
        calories: "520 kcal",
      },
      {
        id: "saffron-gelato-trio",
        name: "Saffron Gelato Trio",
        description: "House-churned gelato: Persian Saffron Honey, Pistachio Mastic and 72% Dark Chocolate.",
        price: 10,
        badge: "VEGETARIAN",
        image: "/images/dish-fruit-tart.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Espresso Ristretto",
        ingredients: ["Persian Saffron", "Chios Mastic", "Valrhona Chocolate", "Organic Cream"],
        calories: "310 kcal",
      },
      {
        id: "kunafa-royale",
        name: "Kunafa Royale",
        description: "Golden kataifi pastry, melting akawi cheese, crushed pistachios and warm blossom infusion.",
        price: 15,
        badge: "CHEF'S PICK",
        image: "/images/dish-lava-cake.jpg",
        dietary: ["All", "Vegetarian"],
        winePairing: "Château Ksara Sweet Vintage",
        ingredients: ["Kataifi Crust", "Akawi Cheese", "Pistachios", "Blossom Syrup"],
        calories: "560 kcal",
      },
    ],
  },
  {
    id: "beverages",
    label: "Beverages",
    icon: "beverages",
    count: 11,
    eyebrow: "CELLAR & APOTHECARY",
    title: "Beverages & Cellar",
    subtitle: "Copper-brewed coffee, mountain botanical infusions, and reserve cellar allocations.",
    collectionBadge: "SOMMELIER CELLAR",
    bannerImage: "/images/candlelight.jpg",
    items: [
      {
        id: "cardamom-lebanese-coffee",
        name: "Lebanese Cardamom Coffee",
        description: "Slow-brewed in copper rakweh, crushed green cardamom pods and orange blossom water.",
        price: 6,
        badge: "POPULAR",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Medjool Date Pairing",
        ingredients: ["Single-Estate Dark Roast", "Green Cardamom", "Orange Blossom Water"],
        calories: "15 kcal",
      },
      {
        id: "sage-wild-lemon",
        name: "Sage & Wild Lemon Infusion",
        description: "Steeped mountain sage, muddled garden mint, local wildflower honey and sparkling spring water.",
        price: 8,
        badge: "VEGETARIAN",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Mezze Pairing",
        ingredients: ["Mountain Sage", "Wild Mint", "Blossom Honey", "Sparkling Water"],
        calories: "65 kcal",
      },
      {
        id: "pomegranate-blossom-spritz",
        name: "Pomegranate Blossom Spritz",
        description: "Cold-pressed pomegranate juice, rose water cordial, elderflower soda and garden mint.",
        price: 11,
        badge: "CHEF'S PICK",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Aperitif",
        ingredients: ["Ruby Pomegranate", "Rose Water", "Elderflower Soda", "Fresh Mint"],
        calories: "90 kcal",
      },
      {
        id: "chateau-musar-2016",
        name: "Château Musar Red 2016",
        description: "Bekaa Valley reserve vintage, notes of dark plum, dried fig, Mediterranean cedar and sweet spices.",
        price: 18,
        badge: "CHEF'S PICK",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Charred Lamb Chops",
        ingredients: ["Cabernet Sauvignon", "Cinsault", "Carignan", "Bekaa Valley"],
        calories: "140 kcal",
      },
      {
        id: "arak-ice",
        name: "Traditional Arak & Crystal Ice",
        description: "Triple-distilled Ksarak with fragrant mountain aniseed, served traditionally with spring water.",
        price: 12,
        badge: "POPULAR",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Cold Mezze",
        ingredients: ["Distilled Grapes", "Mountain Aniseed", "Spring Ice"],
        calories: "110 kcal",
      },
      {
        id: "iced-karak-tea",
        name: "Iced Royal Karak Tea",
        description: "Slow-simmered Assam black tea, evaporated milk, saffron threads and crushed cardamom.",
        price: 7,
        badge: "POPULAR",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Cardamom Date Pudding",
        ingredients: ["Assam Black Tea", "Evaporated Milk", "Saffron", "Cardamom"],
        calories: "120 kcal",
      },
      {
        id: "orange-blossom-lemonade",
        name: "Orange Blossom Lemonade",
        description: "Freshly squeezed coastal lemons, organic blossom water, raw cane syrup and mint sprig.",
        price: 8,
        badge: "VEGETARIAN",
        image: "/images/pea-soup.png",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Starters & Calamari",
        ingredients: ["Coastal Lemons", "Blossom Water", "Cane Syrup", "Mint"],
        calories: "85 kcal",
      },
      {
        id: "beirut-botanical-gin",
        name: "Beirut Botanical Gin & Tonic",
        description: "Artisanal Levantine botanical gin, pink peppercorns, cucumber ribbons and Mediterranean tonic.",
        price: 15,
        badge: "CHEF'S PICK",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Starters & Seafood",
        ingredients: ["Levantine Gin", "Pink Peppercorn", "Cucumber", "Tonic Water"],
        calories: "160 kcal",
      },
      {
        id: "smoked-fig-old-fashioned",
        name: "Smoked Fig Old Fashioned",
        description: "Oak-aged bourbon, smoked mission fig syrup, walnut bitters and charred orange peel.",
        price: 16,
        badge: "CHEF'S PICK",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Braised Short Rib",
        ingredients: ["Aged Bourbon", "Smoked Fig Syrup", "Walnut Bitters", "Orange Peel"],
        calories: "190 kcal",
      },
      {
        id: "sparkling-spring-water",
        name: "Mountain Sparkling Water",
        description: "Pure mountain spring water, natural carbonation, served chilled with citrus peel.",
        price: 6,
        badge: "VEGETARIAN",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Table Water",
        ingredients: ["Pure Spring Water", "Citrus Twist"],
        calories: "0 kcal",
      },
      {
        id: "fresh-moroccan-mint",
        name: "Fresh Spearmint Green Tea",
        description: "Gunpowder green tea brewed with fresh spearmint leaves and raw sugar crystals.",
        price: 7,
        badge: "POPULAR",
        image: "/images/candlelight.jpg",
        dietary: ["All", "Vegetarian", "Gluten-Free"],
        winePairing: "Baklava & Ashta",
        ingredients: ["Gunpowder Green Tea", "Fresh Spearmint", "Raw Sugar"],
        calories: "45 kcal",
      },
    ],
  },
];
