export interface GalleryItem {
  id: string;
  src: string;
  headline: string;
  category: "architecture" | "culinary" | "majlis" | "roastery";
  categoryLabel: string;
  desc: string;
  meta: string;
  badge?: string;
  frame?: string;
  price?: string;
  tags?: string[];
  specs?: string;
  location?: string;
  aperture?: string;
}

export const galleryCategories = [
  { id: "all", label: "All Moments", count: 28 },
  { id: "architecture", label: "The Courtyard & Architecture", count: 8 },
  { id: "culinary", label: "Culinary Masterpieces", count: 10 },
  { id: "majlis", label: "Private Dining & Majlis", count: 4 },
  { id: "roastery", label: "Artisanal Roastery", count: 6 },
] as const;

export const galleryItems: GalleryItem[] = [
  {
    id: "olive-arches-dining",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBlgIambDGnF998SMyTpXGNrNsWW2fW0dRwsV-UMoi9jlDBLDutaFqcdq8D-KJP_6Y6spMnwFhGx38SOheWrRk80bbEkT4xqe_XRMUzYdhdSzjTZLGpRsa_iBqVhG5ZwEcDVn9LI1Qy-KBbR_86nrc91hFrN2qfOrsZJEC-7GM73X8yMK-QRWVFHAhvgcie8TT_wfOTiF8Ucx_p2QzkYotAM7tvQAv0td_vMyFRo8WUl15LEE7OgrV8HCr2AeYJEqO-VL4",
    headline: "The Olive Arches Dining Sanctuary",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Architectural Sanctuary",
    frame: "FRAME 01",
    desc: "Hand-carved limestone colonnades, 300-year-old olive trees, and sun-drenched courtyard dining beneath handwoven khayzaran cane pendants.",
    meta: "Adliya Flagship • Natural Light",
    location: "Block 338, Adliya, Kingdom of Bahrain",
    specs: "Capacity: 140 Guests • Daily Ambiance: 12:00 PM – 11:30 PM",
    aperture: "Aperture f/2.8 • 35mm",
    tags: ["Colonnade", "300-Yr Olive Trees", "Natural Stone"],
  },
  {
    id: "lamb-ashta",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC1hYdqspIbtmLlbTzuu5Ib2nObjLH9otdaxdRJ7fyhkuJh39MZnj9LbTn0zjH-iRpO7hpf6xN-4VsaPhmHGs3juR8Y8sJOTVY9lC3dDB5bnY8bvFhX1FqBiAuBJb1w3ueeb7pixYAjFyR4mTu0XEjfCMaWwYwzqDVNy1OJT-CO_7whau4IJoPtAE_GDxNmnwcc-VGvgF2LesAn7mNiim6d7cMt_Tt7BS77i-XJ4cxnKWyucIjzr1E13Q",
    headline: "Slow-Braised Lamb Ashta with Saffron Puree",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "Signature Entrée",
    frame: "PLATE 01",
    price: "BD 14.50",
    desc: "Twelve-hour slow simmer, infused with cardamom pods, wild pomegranate reduction, and toasted pine kernel dust on handmade stoneware ceramic.",
    meta: "Signature Entrée • Grass-Fed",
    location: "Kitchen Pass, Gibran & Co.",
    specs: "12-Hour Simmer • Organic Saffron",
    aperture: "Aperture f/2.4 • Macro",
    tags: ["Grass-Fed", "Heritage Spices", "Clay Oven"],
  },
  {
    id: "herb-veloute",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyiTJ2zQkazH_t-9GY80CIOtmkgy1Ru91ahsXoyPrtRGCrx_-tUaqkRibSbmNJuQHGeGSduvgzcCB7hLifyxSIeZeM7d3YAFmXj8o6htQVEaCg3VIxRtGQoPoFA0hK3xfYAFrb1-jlaQUOItb3XxE9fRXxUVhV0geV5ByL1aKZgmsSV31LXKNrBPX-Kdh0n8_ZIh1POxR9rNYMUDqgmytyTDLxzrNc48KA7dY6EDgzaXS6fj5IG8I4Dw",
    headline: "Wild Sorrel & Herb Velouté",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "First Course",
    frame: "PLATE 02",
    price: "BD 6.80",
    desc: "Fresh garden herbs, velvet almond cream swirl, hand-roasted pumpkin seeds, and early-harvest Koura olive drizzle.",
    meta: "First Course • Vegan Organic",
    location: "Cold Larder Station",
    specs: "Cold-Pressed Koura Oil • Single Estate",
    aperture: "Aperture f/2.0 • 50mm",
    tags: ["Vegan Organic", "Cold-Pressed Harvest", "Almond Crema"],
  },
  {
    id: "wine-cellar-majlis",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuA4VuX-JMMak0UlBni8lZ34FtLO5vQaEcTS7fu0RHk0GddnPOeut6j4Lhvwbr-mVIfHnlhZFl3h8S_LS1ozNB6NUZ4NLo52uippP2W8pDbEHr1DVlFrUpialbShUNqDJBV4RlF6jn2AxDaHz0XzzHOz9bsVHToNJlt-RveVMQz8DoMrAoMlCVwC6V9Czi5RoymIadLVoxY5rpX4qvv1JGGxTkD_mD8K07baKn5hcQ5fjBzYHv9cLtPmUg",
    headline: "The Candlelit Wine Cellar & Majlis",
    category: "majlis",
    categoryLabel: "Private Dining & Majlis",
    badge: "Twilight Evenings",
    frame: "SALON 03",
    price: "Bespoke",
    desc: "Hand-selected natural wines, Lebanese arak infusions, and secluded banquet settings for private celebrations and quiet conversation.",
    meta: "Salon 02 • Intimate Banquets",
    location: "Subterranean Vault, Gibran House",
    specs: "Capacity: 16 Guests • Sommelier Poured",
    aperture: "Aperture f/1.8 • Low-Light",
    tags: ["Low-Intervention Wines", "Private Banquet", "Bespoke Menu"],
  },
  {
    id: "garden-afternoon-light",
    src: "https://lh3.googleusercontent.com/aida/AEtjO1UgZtZBmQy8OWeEW5spzXaAvhr1jWd_ID2lbd7Bo8_TTjh1lV_VG27HEyoLgSy6FqxozuAvgZvQJ7b0OVpn-_Exi1ITYF8OKBGL6HUBK5psGpi8UgUU5vQEa-S-hyz39DGl8pGos2EACwYQVroPt1Ie9tUMCy1Mr8gAsIlXhWk-SgHwExLJhiwSxvLdl2RWvaQjy6duZ0FKOU7GWB2cInBk7D9A9FF1-VL-CguIKm9U9CD9pqqfYGCr9Hea",
    headline: "Afternoon Light in the Garden Patio",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Atmosphere",
    frame: "FRAME 04",
    desc: "Golden hour filtering through arched floor-to-ceiling iron casements, setting the tempo for slow-living coffee & mezza.",
    meta: "Frame 04 • Afternoon Ambiance",
    location: "Veranda Wing, Adliya",
    specs: "Floor-to-Ceiling Iron Casements",
    aperture: "Aperture f/3.2 • 28mm",
    tags: ["Golden Hour", "Iron Casements", "Slow Living"],
  },
  {
    id: "woodfired-zaatar",
    src: "https://lh3.googleusercontent.com/aida/AEtjO1XaGCWQP4LfVekwm3GDWkKvdWLik0pJGe5qaLjMC3ilUvYklSFnszSOrdbztNUSVNban1Hd218GiRckHDkwX9qhCJdaX5Eta-eb8sW59lU9dkn0fb_AN2AEt7peBttcto5rIlK_PQIrP2TDuWC4oS3frBImqaXNEM94U-Py2Z3XumvyIX00i2b-nKnt34IFnBtnGZcSQY-kmgobYq7a7XD4zsj6oXo0rG9sxKTvyFYUA3zUKwmQLmhF0HTI",
    headline: "Wood-Fired Wild Za'atar & Truffle",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "From the Hearth",
    frame: "STONE OVEN",
    price: "BD 7.20",
    desc: "48-hour cold fermented wild sourdough topped with wild thyme picked from Jabal Amel, labneh crema, and summer truffle.",
    meta: "From the Hearth • Stone Oven",
    location: "Wood Hearth, Gibran Bakery",
    specs: "48-Hour Wild Fermentation • 400°C Beechwood",
    aperture: "Aperture f/2.5 • 40mm",
    tags: ["Wild Thyme", "Sourdough", "Black Truffle"],
  },
  {
    id: "roastery-cezve",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtv3zNJxVvlFhga0yqyMWG5th-GfsxIF2-eyJbF1lEWWmColTMQ0e91lYJ0UxNzP0KwttiomzR3rGaGY54Ze1tyMfwngl5AhqJ5lBe29MDLuzxhe0FLbgv3GW4q9MSjT9D9FQwu9OwdXf_lBG9AGy55YwuO1sD19QKqNfN84FavS1qo7_5alOBvJxMcoECquf2YZLkBZ_hUt4g3foC4ahy9FPS4yzWFned5yAGjy1RiC_0_Rn-oBBwlQ",
    headline: "The Roastery: Cardamom Dark Roast Cezve",
    category: "roastery",
    categoryLabel: "Artisanal Roastery",
    badge: "Roastery Craft",
    frame: "ROAST NO. 12",
    price: "BD 4.20",
    desc: "Traditional hand-hammered brass cezve slow-brewed on hot sand, infusing single-estate Ethiopian beans with freshly crushed cardamom pods.",
    meta: "Ritual 07 • Hot Sand Brewing",
    location: "Artisanal Coffee Bar",
    specs: "Hot Golden Sand • Single Estate Harari Beans",
    aperture: "Aperture f/2.2 • 50mm",
    tags: ["Hot Sand Brewing", "Green Cardamom", "Hammered Brass"],
  },
  {
    id: "olive-grove-arcade",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuB7MP1MWdaweFGDZvUJ47zmLO5Op8FWGUtcChYsWQ8SSHzVp-MfFnThjJckDU80Sg4_27ZafjHXtk8dfvLxMYTGQzFIaYuQy1rZmvqeT8c4SImZJkLsx3QNTLXoevV0l758hBkMMLeSTjfhjJ4f8L2956FkMn7dtoBefDanF3JmKhOzk55G4R7-zAJ1Q4_lRP5-5kCtEp8GEO3fFibPzd-rEezE0QN1W6S73iX072qARlkAoL4Rk366cA",
    headline: "Centuries-Old Olive Grove & Arcade",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Living Heritage",
    frame: "FRAME 08",
    desc: "Living olive trees preserved in the heart of our Adliya courtyard, shaded under natural muslin canopies with stone water rills.",
    meta: "Botanical Heart • 300+ Years",
    location: "Courtyard Center, Adliya",
    specs: "Ancient Specimens • Microclimate Misting",
    aperture: "Aperture f/4.0 • 24mm",
    tags: ["300+ Years Old", "Heritage Landscape", "Al Fresco"],
  },
  {
    id: "plating-pass-craft",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC_Uel7yy6HX30oMEQJirO1mfUHXRAbKxo6xFW_GxlXOYw0N66sr3ytfJ3g0z0Jg4Fq284NTzMGTnehl9479EH-DBpWjjsU4lWEK8QgU2CuSCo3iL4ixRV8zQZlMy8_jVjjmOv4-0F7Wr2vYJ9jNPWbJ_f2UosAioTmBkPH6_dMH5hF4ZWx1nXE19mInzI6Jp8A3Uwrwu8vZgZBGJcRwcHGtCh5p_-YDp1_HoEvBdLR7gMg9x0F68mXSw",
    headline: "The Art of Plating: Flora & Fire",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "Kitchen Pass",
    frame: "CRAFT 05",
    desc: "Executive chef delicately placing organic elderflower blossoms and sumac emulsion with brass plating tweezers onto a slow-roasted heritage dish.",
    meta: "Kitchen Pass • Precision Craft",
    location: "Main Kitchen Pass",
    specs: "Bespoke Plating • Botanical Garnishes",
    aperture: "Aperture f/1.8 • 85mm",
    tags: ["Chef Craft", "Precision", "Botanical Garnishes"],
  },
  {
    id: "guest-moment-lunch",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBK6xvFpMsmrtdJKK3eaOX6DT2QwzAd20tNI1xabkBW4C9Q9mdEDnsgSyzSJ7lp9lY3brd9bsYxxwggVqgreHH-JrjIVl41VbVwgX7hvNBfJROqIfjsrsq4W7nCZHovjx33_PMrZhDi7NFQD4JveXi_Y6JrVdwBDzztxnphfPBAzwoH4JCKZfnY0LTr3AcfbeO8RbRCbGVaTzwcMpXyHbg6xTVWh6k4bQjVG4-OHDx9VXZyAXnZAuD9GA",
    headline: "Courtyard Mezza Gathering by Olive Trees",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Guest Moment",
    frame: "GUEST 01",
    desc: "Guest snapshot of an abundant sunlit lunch table spread with warm mezza small plates, freshly baked taboon flatbreads, and wine glasses.",
    meta: "Guest Moment • Friday Gathering",
    location: "Courtyard Pergola Table 12",
    specs: "Family Style Mezza Feast",
    aperture: "Aperture f/2.8 • 35mm",
    tags: ["Mezza Feast", "Friday Gathering", "Shared Memories"],
  },
  {
    id: "guest-moment-wine",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMp4eAIdl02U5T7bJ7BtwRQjX1r8j4Cw-Cf3aCgDXqa_FiaoSBGkMMQtryYikcDhP4spHBjt0ktjveyvQhvx2MNqYTJPrpxgenQEOnBeperiHsCwUWN695nncvTnkQRgUv7veAhwri2bKSul4DuBSc4rj4czvnZHOfQl8kBq_7GaVMDREknQm9AA_WgfAGB-TOmzh9Se21bZsfbog646Ew_gBWq9YM6PkDDv-9-9KxM-xtqvOt1as8yw",
    headline: "Candlelit Amber Toast in the Courtyard",
    category: "majlis",
    categoryLabel: "Private Dining & Majlis",
    badge: "Twilight Gathering",
    frame: "GUEST 02",
    desc: "Two crystal glasses toasting with amber natural orange wine over glowing candlelight in the quiet evening courtyard.",
    meta: "Guest Moment • Twilight",
    location: "Lantern Terrace, Gibran House",
    specs: "Biodynamic Skin-Contact Wine",
    aperture: "Aperture f/1.4 • 50mm",
    tags: ["Amber Wine", "Candlelight", "Toasting"],
  },
];

export const exhibitionReelItems = [
  {
    itemIndex: 1,
    id: "lamb-ashta",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuC1hYdqspIbtmLlbTzuu5Ib2nObjLH9otdaxdRJ7fyhkuJh39MZnj9LbTn0zjH-iRpO7hpf6xN-4VsaPhmHGs3juR8Y8sJOTVY9lC3dDB5bnY8bvFhX1FqBiAuBJb1w3ueeb7pixYAjFyR4mTu0XEjfCMaWwYwzqDVNy1OJT-CO_7whau4IJoPtAE_GDxNmnwcc-VGvgF2LesAn7mNiim6d7cMt_Tt7BS77i-XJ4cxnKWyucIjzr1E13Q",
    badge: "Plate 01",
    title: "Slow-Braised Lamb Ashta",
    price: "BD 14.50",
    desc: "Twelve-hour slow cardamom simmer & pomegranate glaze.",
  },
  {
    itemIndex: 2,
    id: "herb-veloute",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuCyiTJ2zQkazH_t-9GY80CIOtmkgy1Ru91ahsXoyPrtRGCrx_-tUaqkRibSbmNJuQHGeGSduvgzcCB7hLifyxSIeZeM7d3YAFmXj8o6htQVEaCg3VIxRtGQoPoFA0hK3xfYAFrb1-jlaQUOItb3XxE9fRXxUVhV0geV5ByL1aKZgmsSV31LXKNrBPX-Kdh0n8_ZIh1POxR9rNYMUDqgmytyTDLxzrNc48KA7dY6EDgzaXS6fj5IG8I4Dw",
    badge: "Plate 02",
    title: "Wild Sorrel & Herb Velouté",
    price: "BD 6.80",
    desc: "Velvet almond cream, toasted pumpkin seeds, Koura olive oil.",
  },
  {
    itemIndex: 3,
    id: "wine-cellar-majlis",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuA4VuX-JMMak0UlBni8lZ34FtLO5vQaEcTS7fu0RHk0GddnPOeut6j4Lhvwbr-mVIfHnlhZFl3h8S_LS1ozNB6NUZ4NLo52uippP2W8pDbEHr1DVlFrUpialbShUNqDJBV4RlF6jn2AxDaHz0XzzHOz9bsVHToNJlt-RveVMQz8DoMrAoMlCVwC6V9Czi5RoymIadLVoxY5rpX4qvv1JGGxTkD_mD8K07baKn5hcQ5fjBzYHv9cLtPmUg",
    badge: "Salon 03",
    title: "Candlelit Wine Cellar & Majlis",
    price: "Bespoke",
    desc: "Natural low-intervention wines & secluded evening banquets.",
  },
  {
    itemIndex: 6,
    id: "roastery-cezve",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtv3zNJxVvlFhga0yqyMWG5th-GfsxIF2-eyJbF1lEWWmColTMQ0e91lYJ0UxNzP0KwttiomzR3rGaGY54Ze1tyMfwngl5AhqJ5lBe29MDLuzxhe0FLbgv3GW4q9MSjT9D9FQwu9OwdXf_lBG9AGy55YwuO1sD19QKqNfN84FavS1qo7_5alOBvJxMcoECquf2YZLkBZ_hUt4g3foC4ahy9FPS4yzWFned5yAGjy1RiC_0_Rn-oBBwlQ",
    badge: "Roast 12",
    title: "Cardamom Dark Cezve Pour",
    price: "BD 4.20",
    desc: "Single-origin Harari beans ground with organic cardamom pods.",
  },
];

export const guestSocialStream = [
  {
    itemIndex: 9,
    handle: "@nadia.wanderer",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuBK6xvFpMsmrtdJKK3eaOX6DT2QwzAd20tNI1xabkBW4C9Q9mdEDnsgSyzSJ7lp9lY3brd9bsYxxwggVqgreHH-JrjIVl41VbVwgX7hvNBfJROqIfjsrsq4W7nCZHovjx33_PMrZhDi7NFQD4JveXi_Y6JrVdwBDzztxnphfPBAzwoH4JCKZfnY0LTr3AcfbeO8RbRCbGVaTzwcMpXyHbg6xTVWh6k4bQjVG4-OHDx9VXZyAXnZAuD9GA",
    alt: "Guest mezza lunch spread",
  },
  {
    itemIndex: 10,
    handle: "@kareem.tasting",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDMp4eAIdl02U5T7bJ7BtwRQjX1r8j4Cw-Cf3aCgDXqa_FiaoSBGkMMQtryYikcDhP4spHBjt0ktjveyvQhvx2MNqYTJPrpxgenQEOnBeperiHsCwUWN695nncvTnkQRgUv7veAhwri2bKSul4DuBSc4rj4czvnZHOfQl8kBq_7GaVMDREknQm9AA_WgfAGB-TOmzh9Se21bZsfbog646Ew_gBWq9YM6PkDDv-9-9KxM-xtqvOt1as8yw",
    alt: "Guest wine toast at candlelight",
  },
  {
    itemIndex: 6,
    handle: "@layla.arch",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuDtv3zNJxVvlFhga0yqyMWG5th-GfsxIF2-eyJbF1lEWWmColTMQ0e91lYJ0UxNzP0KwttiomzR3rGaGY54Ze1tyMfwngl5AhqJ5lBe29MDLuzxhe0FLbgv3GW4q9MSjT9D9FQwu9OwdXf_lBG9AGy55YwuO1sD19QKqNfN84FavS1qo7_5alOBvJxMcoECquf2YZLkBZ_hUt4g3foC4ahy9FPS4yzWFned5yAGjy1RiC_0_Rn-oBBwlQ",
    alt: "Morning coffee pour in copper cezve",
  },
  {
    itemIndex: 7,
    handle: "@salman_bh",
    src: "https://lh3.googleusercontent.com/aida-public/AB6AXuB7MP1MWdaweFGDZvUJ47zmLO5Op8FWGUtcChYsWQ8SSHzVp-MfFnThjJckDU80Sg4_27ZafjHXtk8dfvLxMYTGQzFIaYuQy1rZmvqeT8c4SImZJkLsx3QNTLXoevV0l758hBkMMLeSTjfhjJ4f8L2956FkMn7dtoBefDanF3JmKhOzk55G4R7-zAJ1Q4_lRP5-5kCtEp8GEO3fFibPzd-rEezE0QN1W6S73iX072qARlkAoL4Rk366cA",
    alt: "Courtyard sunset glow through olive trees",
  },
];
