export interface GalleryItem {
  id: string;
  src: string;
  headline: string;
  category: "architecture" | "culinary" | "majlis" | "roastery";
  categoryLabel: string;
  desc: string;
  meta: string;
  badge?: string;
  frame?: string;
  price?: string;
  tags?: string[];
  specs?: string;
  location?: string;
  aperture?: string;
}

export const galleryCategories = [
  { id: "all", label: "All Moments", count: 28 },
  { id: "architecture", label: "The Courtyard & Architecture", count: 8 },
  { id: "culinary", label: "Culinary Masterpieces", count: 10 },
  { id: "majlis", label: "Private Dining & Majlis", count: 4 },
  { id: "roastery", label: "Artisanal Roastery", count: 6 },
] as const;

export const galleryItems: GalleryItem[] = [
  {
    id: "olive-arches-dining",
    src: "/assets/gallery/olive-arches.jpg",
    headline: "The Olive Arches Dining Sanctuary",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Architectural Sanctuary",
    frame: "FRAME 01",
    desc: "Hand-carved limestone colonnades, 300-year-old olive trees, and sun-drenched courtyard dining beneath handwoven khayzaran cane pendants.",
    meta: "Adliya Flagship • Natural Light",
    location: "Block 338, Adliya, Kingdom of Bahrain",
    specs: "Capacity: 140 Guests • Daily Ambiance: 12:00 PM – 11:30 PM",
    aperture: "Aperture f/2.8 • 35mm",
    tags: ["Colonnade", "300-Yr Olive Trees", "Natural Stone"],
  },
  {
    id: "lamb-ashta",
    src: "/assets/gallery/lamb-ashta.jpg",
    headline: "Slow-Braised Lamb Ashta with Saffron Puree",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "Signature Entrée",
    frame: "PLATE 01",
    price: "BD 14.50",
    desc: "Twelve-hour slow simmer, infused with cardamom pods, wild pomegranate reduction, and toasted pine kernel dust on handmade stoneware ceramic.",
    meta: "Signature Entrée • Grass-Fed",
    location: "Kitchen Pass, Gibran & Co.",
    specs: "12-Hour Simmer • Organic Saffron",
    aperture: "Aperture f/2.4 • Macro",
    tags: ["Grass-Fed", "Heritage Spices", "Clay Oven"],
  },
  {
    id: "herb-veloute",
    src: "/assets/gallery/herb-veloute.jpg",
    headline: "Wild Sorrel & Herb Velouté",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "First Course",
    frame: "PLATE 02",
    price: "BD 6.80",
    desc: "Fresh garden herbs, velvet almond cream swirl, hand-roasted pumpkin seeds, and early-harvest Koura olive drizzle.",
    meta: "First Course • Vegan Organic",
    location: "Cold Larder Station",
    specs: "Cold-Pressed Koura Oil • Single Estate",
    aperture: "Aperture f/2.0 • 50mm",
    tags: ["Vegan Organic", "Cold-Pressed Harvest", "Almond Crema"],
  },
  {
    id: "wine-cellar-majlis",
    src: "/assets/gallery/wine-cellar.jpg",
    headline: "The Candlelit Wine Cellar & Majlis",
    category: "majlis",
    categoryLabel: "Private Dining & Majlis",
    badge: "Twilight Evenings",
    frame: "SALON 03",
    price: "Bespoke",
    desc: "Hand-selected natural wines, Lebanese arak infusions, and secluded banquet settings for private celebrations and quiet conversation.",
    meta: "Salon 02 • Intimate Banquets",
    location: "Subterranean Vault, Gibran House",
    specs: "Capacity: 16 Guests • Sommelier Poured",
    aperture: "Aperture f/1.8 • Low-Light",
    tags: ["Low-Intervention Wines", "Private Banquet", "Bespoke Menu"],
  },
  {
    id: "garden-afternoon-light",
    src: "/assets/gallery/garden-light.jpg",
    headline: "Afternoon Light in the Garden Patio",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Atmosphere",
    frame: "FRAME 04",
    desc: "Golden hour filtering through arched floor-to-ceiling iron casements, setting the tempo for slow-living coffee & mezza.",
    meta: "Frame 04 • Afternoon Ambiance",
    location: "Veranda Wing, Adliya",
    specs: "Floor-to-Ceiling Iron Casements",
    aperture: "Aperture f/3.2 • 28mm",
    tags: ["Golden Hour", "Iron Casements", "Slow Living"],
  },
  {
    id: "woodfired-zaatar",
    src: "/assets/gallery/woodfired-zaatar.jpg",
    headline: "Wood-Fired Wild Za'atar & Truffle",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "From the Hearth",
    frame: "STONE OVEN",
    price: "BD 7.20",
    desc: "48-hour cold fermented wild sourdough topped with wild thyme picked from Jabal Amel, labneh crema, and summer truffle.",
    meta: "From the Hearth • Stone Oven",
    location: "Wood Hearth, Gibran Bakery",
    specs: "48-Hour Wild Fermentation • 400°C Beechwood",
    aperture: "Aperture f/2.5 • 40mm",
    tags: ["Wild Thyme", "Sourdough", "Black Truffle"],
  },
  {
    id: "roastery-cezve",
    src: "/assets/gallery/roastery-cezve.jpg",
    headline: "The Roastery: Cardamom Dark Roast Cezve",
    category: "roastery",
    categoryLabel: "Artisanal Roastery",
    badge: "Roastery Craft",
    frame: "ROAST NO. 12",
    price: "BD 4.20",
    desc: "Traditional hand-hammered brass cezve slow-brewed on hot sand, infusing single-estate Ethiopian beans with freshly crushed cardamom pods.",
    meta: "Ritual 07 • Hot Sand Brewing",
    location: "Artisanal Coffee Bar",
    specs: "Hot Golden Sand • Single Estate Harari Beans",
    aperture: "Aperture f/2.2 • 50mm",
    tags: ["Hot Sand Brewing", "Green Cardamom", "Hammered Brass"],
  },
  {
    id: "olive-grove-arcade",
    src: "/assets/gallery/olive-grove.jpg",
    headline: "Centuries-Old Olive Grove & Arcade",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Living Heritage",
    frame: "FRAME 08",
    desc: "Living olive trees preserved in the heart of our Adliya courtyard, shaded under natural muslin canopies with stone water rills.",
    meta: "Botanical Heart • 300+ Years",
    location: "Courtyard Center, Adliya",
    specs: "Ancient Specimens • Microclimate Misting",
    aperture: "Aperture f/4.0 • 24mm",
    tags: ["300+ Years Old", "Heritage Landscape", "Al Fresco"],
  },
  {
    id: "plating-pass-craft",
    src: "/assets/gallery/chef-plating.jpg",
    headline: "The Art of Plating: Flora & Fire",
    category: "culinary",
    categoryLabel: "Culinary Masterpieces",
    badge: "Kitchen Pass",
    frame: "CRAFT 05",
    desc: "Executive chef delicately placing organic elderflower blossoms and sumac emulsion with brass plating tweezers onto a slow-roasted heritage dish.",
    meta: "Kitchen Pass • Precision Craft",
    location: "Main Kitchen Pass",
    specs: "Bespoke Plating • Botanical Garnishes",
    aperture: "Aperture f/1.8 • 85mm",
    tags: ["Chef Craft", "Precision", "Botanical Garnishes"],
  },
  {
    id: "guest-moment-lunch",
    src: "/assets/gallery/guest-lunch.jpg",
    headline: "Courtyard Mezza Gathering by Olive Trees",
    category: "architecture",
    categoryLabel: "The Courtyard & Architecture",
    badge: "Guest Moment",
    frame: "GUEST 01",
    desc: "Guest snapshot of an abundant sunlit lunch table spread with warm mezza small plates, freshly baked taboon flatbreads, and wine glasses.",
    meta: "Guest Moment • Friday Gathering",
    location: "Courtyard Pergola Table 12",
    specs: "Family Style Mezza Feast",
    aperture: "Aperture f/2.8 • 35mm",
    tags: ["Mezza Feast", "Friday Gathering", "Shared Memories"],
  },
  {
    id: "guest-moment-wine",
    src: "/assets/gallery/guest-wine.jpg",
    headline: "Candlelit Amber Toast in the Courtyard",
    category: "majlis",
    categoryLabel: "Private Dining & Majlis",
    badge: "Twilight Gathering",
    frame: "GUEST 02",
    desc: "Two crystal glasses toasting with amber natural orange wine over glowing candlelight in the quiet evening courtyard.",
    meta: "Guest Moment • Twilight",
    location: "Lantern Terrace, Gibran House",
    specs: "Biodynamic Skin-Contact Wine",
    aperture: "Aperture f/1.4 • 50mm",
    tags: ["Amber Wine", "Candlelight", "Toasting"],
  },
];

export const exhibitionReelItems = [
  {
    itemIndex: 1,
    id: "lamb-ashta",
    src: "/assets/gallery/lamb-ashta.jpg",
    badge: "Plate 01",
    title: "Slow-Braised Lamb Ashta",
    price: "BD 14.50",
    desc: "Twelve-hour slow cardamom simmer & pomegranate glaze.",
  },
  {
    itemIndex: 2,
    id: "herb-veloute",
    src: "/assets/gallery/herb-veloute.jpg",
    badge: "Plate 02",
    title: "Wild Sorrel & Herb Velouté",
    price: "BD 6.80",
    desc: "Velvet almond cream, toasted pumpkin seeds, Koura olive oil.",
  },
  {
    itemIndex: 3,
    id: "wine-cellar-majlis",
    src: "/assets/gallery/wine-cellar.jpg",
    badge: "Salon 03",
    title: "Candlelit Wine Cellar & Majlis",
    price: "Bespoke",
    desc: "Natural low-intervention wines & secluded evening banquets.",
  },
  {
    itemIndex: 6,
    id: "roastery-cezve",
    src: "/assets/gallery/roastery-cezve.jpg",
    badge: "Roast 12",
    title: "Cardamom Dark Cezve Pour",
    price: "BD 4.20",
    desc: "Single-origin Harari beans ground with organic cardamom pods.",
  },
];

export const guestSocialStream = [
  {
    itemIndex: 9,
    handle: "@nadia.wanderer",
    src: "/assets/gallery/guest-lunch.jpg",
    alt: "Guest mezza lunch spread",
  },
  {
    itemIndex: 10,
    handle: "@kareem.tasting",
    src: "/assets/gallery/guest-wine.jpg",
    alt: "Guest wine toast at candlelight",
  },
  {
    itemIndex: 6,
    handle: "@layla.arch",
    src: "/assets/gallery/roastery-cezve.jpg",
    alt: "Morning coffee pour in copper cezve",
  },
  {
    itemIndex: 7,
    handle: "@salman_bh",
    src: "/assets/gallery/olive-grove.jpg",
    alt: "Courtyard sunset glow through olive trees",
  },
];
